"""افزودن ستون تصویر بندانگشتی به پیوست‌ها

Revision ID: 223993938f2f
Revises: 8a865d767aad
Create Date: 2026-08-15 11:58:21.514378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223993938f2f'
down_revision: Union[str, None] = '8a865d767aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('thumbnail_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'thumbnail_path')
    # ### end Alembic commands ###
