"""بهبود مقیاس‌پذیری: ایندکس‌های گمشده و رفع CASCADE خطرناک import_batches

Revision ID: 860baf725c3d
Revises: 7ad35794c2a0
Create Date: 2026-08-21 03:38:51.438458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860baf725c3d'
down_revision: Union[str, None] = '7ad35794c2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attachments_trade_id', 'attachments', ['trade_id'], unique=False)
    op.create_index('ix_checklist_items_template_id', 'checklist_items', ['template_id'], unique=False)
    op.create_index('ix_field_options_field_id', 'field_options', ['field_id'], unique=False)
    op.create_index('ix_import_batches_account_id', 'import_batches', ['account_id'], unique=False)
    op.drop_constraint('import_batches_account_id_fkey', 'import_batches', type_='foreignkey')
    op.create_foreign_key(
        'import_batches_account_id_fkey', 'import_batches', 'accounts',
        ['account_id'], ['id'], ondelete='RESTRICT'
    )
    op.create_index('ix_mistake_costs_mistake_tag_id', 'mistake_costs', ['mistake_tag_id'], unique=False)
    op.create_index('ix_trade_checklist_answers_checklist_item_id', 'trade_checklist_answers', ['checklist_item_id'], unique=False)
    op.create_index('ix_trade_field_values_field_id', 'trade_field_values', ['field_id'], unique=False)
    op.create_index('ix_trade_field_values_value_json_gin', 'trade_field_values', ['value_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_trades_checklist_template_id', 'trades', ['checklist_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_checklist_template_id', table_name='trades')
    op.drop_index('ix_trade_field_values_value_json_gin', table_name='trade_field_values', postgresql_using='gin')
    op.drop_index('ix_trade_field_values_field_id', table_name='trade_field_values')
    op.drop_index('ix_trade_checklist_answers_checklist_item_id', table_name='trade_checklist_answers')
    op.drop_index('ix_mistake_costs_mistake_tag_id', table_name='mistake_costs')
    op.drop_constraint('import_batches_account_id_fkey', 'import_batches', type_='foreignkey')
    op.create_foreign_key(
        'import_batches_account_id_fkey', 'import_batches', 'accounts',
        ['account_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_index('ix_import_batches_account_id', table_name='import_batches')
    op.drop_index('ix_field_options_field_id', table_name='field_options')
    op.drop_index('ix_checklist_items_template_id', table_name='checklist_items')
    op.drop_index('ix_attachments_trade_id', table_name='attachments')
    # ### end Alembic commands ###
